version: "3.8"
services:
  configserver:
    image: dilipkumarmj/configserver:latest
    ports:
      - "8071:8071"
    networks:
      - dilip-network
  accounts:
    image: dilipkumarmj/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - dilip-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  loans:
    image: dilipkumarmj/loans:latest
    ports:
      - "8090:8090"
    networks:
      - dilip-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  cards:
    image: dilipkumarmj/cards:latest
    ports:
      - "9000:9000"
    networks:
      - dilip-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
networks:
  dilip-network:

